### ISSUE TITLE
Build & send transaction from the UI

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet-desktop#46] opened 2022-01-07 15:35 UTC
Some users are willing to send handcrafted transaction but doesn't know how to craft one. Having a dynamic form to help them doing it could be good.

**Comment by notbot00** [comment] 2022-11-03 12:33
closing this as a duplicate of https://github.com/vegaprotocol/vegawallet-desktop/issues/230

**Closed by notbot00** 2022-11-03 12:33 UTC
Labels: feature, desktop-wallet, ui
